apiVersion: v1
kind: Service
metadata:
  name: kube-service
  namespace: kubeapp
spec:
  selector:
    app: kube
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP